exports.deviceName= 'vibration';
exports.resourcePath= 'tcp://158.42.105.178:1883';
exports.sensorName= 'Sensor1';
exports.topic= '/CISSGateway/#';
exports.username= '';
exports.password= '';
exports.security= false;
exports.jsonPath= '$..fields[?(@.name=="Pressure")]';
exports.type= 'JSON';